environment:
  vsversion: none
  arch: default
  matrix:
    - platform: vs
      vsversion: 2017
      arch: x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - platform: vs
      vsversion: 2017
      arch: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

configuration: Release

init:
  - echo %platform%
  - echo %vsversion%
  - echo %arch%
  - if %platform%==vs ( set "makegen=Visual Studio" )
  - if %vsversion%==2017 ( set "makegen=%makegen% 15 %vsversion%" )
  - if %arch%==x64 ( set "makegen=%makegen% Win64" )

before_build:
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -G %makegen%

build_script:
  - msbuild /p:Platform=%arch% "ALL_BUILD.vcxproj"
