environment:
  vsversion: none
  arch: default
  matrix:
    - platform: vs
      vsversion: 2013
      arch: x86

    - platform: vs
      vsversion: 2015
      arch: x86

    - platform: vs
      vsversion: 2017
      arch: x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - platform: vs
      vsversion: 2013
      arch: x64

    - platform: vs
      vsversion: 2015
      arch: x64

    - platform: vs
      vsversion: 2017
      arch: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - platform: mingw32

init:
  - echo %platform%
  - echo %vsversion%
  - echo %arch%
  - if %platform%==vs set "cmakegen=Visual Studio"
  - if %platform%==mingw32 set PATH=C:\MinGW\bin;%PATH%
  - if %platform%==mingw32 set "cmakegen=MinGW Makefiles"
  - if %vsversion%==2013 set "cmakegen=%cmakegen% 12 %vsversion%"
  - if %vsversion%==2015 set "cmakegen=%cmakegen% 14 %vsversion%"
  - if %vsversion%==2017 set "cmakegen=%cmakegen% 15 %vsversion%"
  - if %arch%==x64 set "cmakegen=%cmakegen% Win64"

build_script:
  - cmake --version
  - echo "%cmakegen%"
  - if %platform%==vs mkdir build
  - if %platform%==vs cd build
  - if %platform%==vs cmake .. -G "%cmakegen%"
  - if %platform%==vs msbuild /p:Platform=%arch% /p:Configuration=Debug "ALL_BUILD.vcxproj"
  - if %platform%==vs msbuild /p:Platform=%arch% /p:Configuration=Release "ALL_BUILD.vcxproj"
  - if %platform%==mingw32 mkdir build-debug
  - if %platform%==mingw32 pushd build-debug
  - if %platform%==mingw32 cmake -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles" ..
  - if %platform%==mingw32 mingw32 mingw32-make
  - if %platform%==mingw32 popd
  - if %platform%==mingw32 mkdir build-release
  - if %platform%==mingw32 pushd build-release
  - if %platform%==mingw32 cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ..
  - if %platform%==mingw32 mingw32 mingw32-make
  - if %platform%==mingw32 popd
