image:
  - Visual Studio 2017
configuration:
  - Debug
  - Release
platform:
  - x86
  - x64
environment:
  matrix:
    - arch: Win64

init:
  - set garch=
  - if "%arch%"=="Win64" ( set garch= Win64)
  - echo %garch%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%garch%" )
  - echo %generator%

before_build:
  - cmd: |-
      mkdir build
      cd build
      cmake --version
      cmake .. -G %generator%

build:
  project: build\flshm.sln
  verbosity: minimal
  parallel: true
