image:
  - Visual Studio 2017
configuration:
  - Release
  - Debug
platform:
  - x64
environment:
  matrix:
    - arch: Win64

before_build:
  - cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G "Visual Studio 15 2017"
